-- MySQL Script generated by MySQL Workbench
-- Mon Jul  4 21:26:00 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CadastroLogin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CadastroLogin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CadastroLogin` DEFAULT CHARACTER SET utf8 ;
USE `CadastroLogin` ;

-- -----------------------------------------------------
-- Table `CadastroLogin`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CadastroLogin`.`Usuario` (
  `id_usr` INT NOT NULL AUTO_INCREMENT,
  `usr_nm` VARCHAR(45) NOT NULL,
  `usr_email` VARCHAR(45) NOT NULL,
  `usr_sn` VARCHAR(45) NOT NULL,
  `usr_sbnm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usr`),
  UNIQUE INDEX `id_usr_UNIQUE` (`id_usr` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CadastroLogin`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CadastroLogin`.`telefone` (
  `id_tlf` INT NOT NULL AUTO_INCREMENT,
  `tlf_cl` VARCHAR(45) NOT NULL,
  `tlf_rs` VARCHAR(45) NULL,
  `tlf_cm` VARCHAR(45) NULL,
  `Usuario_id_usr` INT NOT NULL,
  PRIMARY KEY (`id_tlf`),
  UNIQUE INDEX `id_tlf_UNIQUE` (`id_tlf` ASC),
  INDEX `fk_telefone_Usuario_idx` (`Usuario_id_usr` ASC),
  CONSTRAINT `fk_telefone_Usuario`
    FOREIGN KEY (`Usuario_id_usr`)
    REFERENCES `CadastroLogin`.`Usuario` (`id_usr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CadastroLogin`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CadastroLogin`.`Endereco` (
  `id_end` INT NOT NULL AUTO_INCREMENT,
  `end_cs` VARCHAR(45) NOT NULL,
  `end_qd` VARCHAR(45) NOT NULL,
  `end_rua` VARCHAR(45) NOT NULL,
  `Usuario_id_usr` INT NOT NULL,
  PRIMARY KEY (`id_end`),
  UNIQUE INDEX `id_end_UNIQUE` (`id_end` ASC),
  INDEX `fk_Endereco_Usuario1_idx` (`Usuario_id_usr` ASC),
  CONSTRAINT `fk_Endereco_Usuario1`
    FOREIGN KEY (`Usuario_id_usr`)
    REFERENCES `CadastroLogin`.`Usuario` (`id_usr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
